### ISSUE TITLE
Makefile/debug requirements

### ISSUE THREAD

**Issue by jared321** [Flash-X/Flash-X-Test#33]
I have setup a production Jenkins job for use with GCC and a job for use with Intel.  For GCE, the former uses the Flash-X makefile called `Makefile.h`; the latter, `Makefile.h.Intel`.  Therefore, to run the Intel suite, I would need to add to each line in `test.info` something like `-makefile Intel`.  To the best of my knowledge, this information is not yet part of the syntax for the test suite language so that I cannot specify this information in the suite file.

A few use cases:
* Suppose that I have a suite that I use for running tests on Milhoja with the Intel compiler suite.  Normally, the majority of tests in the suite run in production mode.  As part of debugging big developments or preparing for a major release, I would like to run all such tests in debug mode as a sanity check.  Ideally, I would like to do so without having to alter my suite file, a `test.info`, or altering/redoing my flashxtest config file.
* For maintenance sake, it could be good to save a create/maintain a single production suite file and use that same file to run the same tests but with different software stacks (e.g., GCC and Intel).  Ideally, we could do this without having to edit either the suite file or any `test.info` manually.

Possible requirements:
* If the necessary variable exists in the FlashTest config file, add a flag such as `--makefile <user specified value>`to `flashxtest init` so that users can specify that all tests in generated `test.info` files should contain `-makefile <user specified value>`.
* Extend `flashxtest run-suite` to accept the flags `--debug` and `--makefile <user specified value>`.  When given, each test in the `test.info` files to run will have these values appended to them automatically.

**Comment by akashdhruv** [comment]
Closing this since we can use options `-as` to pass makefile name during `setup-suite` and also directly within `suite` files
