### ISSUE TITLE
Detect properly if FlashTest has written to ERROR file

### ISSUE THREAD

**Issue by kweide** [Flash-X/Flash-X-Test#34]
The following lines at the top of `error.sh` do not work properly in the context in which `error.sh` is invoked:
```bash
# Try to alert that new messages were just written to the ERRORS file.                                                                                                         
# We do not know for sure whether they are from this run, though.                                                                                                              
if [ \( -r $FLASHTEST_BASE/ERROR \) -a \( "$FLASHTEST_BASE/ERROR" -nt "$FLASHTEST_OUTPUT" \) ]; then
        echo "WARNING: $FLASHTEST_BASE/ERROR appears to have some new messages."
        echo "         Here are the last two lines of them:"
        tail -n 2 "$FLASHTEST_BASE/ERROR"
fi
```

(see various Console files from Jenkins runs that invoke `flashxtest run-suite`).

The point of this snippet is to detect whether the file `ERROR` is newer than (`test ... -nt ...`) something that was created (or time-stamped, i.e., `touch`'d) when FlashTest was started (or just immediately before). That logic made sense in some past time, when the `ERROR` file used to be kept in a place that survived FlashTest invocation. It does not make much sense now.

It would be best to replace those lines with some Pythonic way to detect whether ERROR has been written to. And/or just make sure that the run starts out with an empty ERROR file, and jsut detect whether it is nonempty after FlashTest is done.

**Comment by akashdhruv** [comment]
#54
